name: 'PAPIProxyBridge'
description: 'A bridge library plugin for using PlaceholderAPI on proxy servers'
author: 'William278'
website: 'https://william278.net/'
version: '${version}'
main: 'net.william278.papiproxybridge.BukkitPAPIProxyBridge'
api-version: 1.16
depend: [ PlaceholderAPI ]