name: 'PAPIProxyBridge'
description: 'Bridge plugin for using PlaceholderAPI on proxy servers'
author: 'William278'
website: 'https://william278.net/'
main: 'net.william278.papiproxybridge.BukkitPAPIProxyBridge'
version: '${version}'
api-version: 1.16
depend: [ PlaceholderAPI ]